version: "3"

services:
  db:
    image: postgres
    container_name: postgres-db-prod
    environment:
      - POSTGRES_DB=sample_database_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=127.0.0.1
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./mediafiles:/media
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: django-web-prod
    restart: on-failure
    volumes:
      - .:/code
    command: bash -c "python manage.py makemigrations sample_app --noinput && python manage.py migrate --noinput &&  gunicorn django_docker_setup.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8080:8080"
    depends_on:
      - db

