version: "3"

services:
  db:
    image: postgres
    container_name: postgres-db-prod
    environment:
      - POSTGRES_DB=sample_database_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=127.0.0.1
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data


  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf_ssl.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot 
      - ./static:/static
      - ./mediafiles:/media
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 5d & wait $${!}; done;'"


  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django-web-prod
    restart: on-failure
    volumes:
      - .:/code
    command: bash -c "python manage.py makemigrations sample_app --noinput && python manage.py migrate --noinput &&  gunicorn django_docker_setup.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8080:8080"
    depends_on:
      - db

